### ISSUE TITLE
The generated import goPackageName no longer honour the package name

### ISSUE THREAD

**Issue by kinyat** [micro/protoc-gen-micro#42] opened 2019-04-10 00:50 UTC
The removed logic located in [here](https://github.com/micro/protoc-gen-micro/compare/8936c52435e55ac5590fb6f9a7e2ed374a561ae9...master#diff-338bea067d2a01b69c90f1c032c6a24bL309)

It used to generate the package name based on the package name defined in the target `.proto` file however it has been removed.

This is causing an issue when the package name conflict with other generated code.

In our case, one of the generated interface names has the same name as the import package name. After I rollback to `8936c5` everything work just fine.

Can we add that logic back to https://github.com/micro/protoc-gen-micro/blob/master/generator/generator.go#L527, please?

**Comment by asim** [comment] 2019-04-10 06:27
@swedishborgie what do you think?

**Comment by swedishborgie** [comment] 2019-04-10 13:42
@kinyat could you please provide a simple example of a protobuf that exhibits the change in behavior you're describing?

There were some significant changes to how names get generated when we merged in the upstream generator changes but it should definitely still be respecting the `go_package` option. Once I have an example of what you're seeing I should be able to determine if we can safely restore the old behavior, or if the behavior changed for a good reason.

**Comment by kinyat** [comment] 2019-04-15 04:51
@swedishborgie 
Sorry for the confusion. 
When I say package name, it is not the `go_package` but the `package` (see below)

in `my.srv.opps/proto/opps.proto`
```
package my.srv.opps; // used to honour this and name the variable as `my_srv_opps`
option go_package = "opps";

service Opps {
}

message MyMessage {
  string test = 1
}
```

in `my.another.srv.opps/proto/opps.proto`
```
package my.another.srv.opps;
import "my.srv.opps/proto/opps.proto";

service Opps { // notice that I am using the same service name in different `package`
  rpc UseOpps(Request) returns (my.srv.opps.MyMessage) // used to generate my_srv_opps.MyMessage
}
```

The generated `my.another.srv.opps/opps.micro.go` will have something like

```
import opps "my.srv.opps/proto/opps"

func RegisterOppsHandler(s server.Server, hdlr OppsHandler, opts ...server.HandlerOption) error {
	type opps interface {
                UseOpps(ctx content.Context, in *handleUseOpps, out *opps.MyMessage) // wrong. This opps is refering to the `type opps interface`
        }
}
```

In the old version, it will be something like below and works

``
import my_srv_opps "my.srv.opps/proto/opps"

func RegisterOppsHandler(s server.Server, hdlr OppsHandler, opts ...server.HandlerOption) error {
	type opps interface {
                UseOpps(ctx content.Context, in *handleUseOpps, out *my_srv_opps.MyMessage) // this is correct
        }
}
``

**Comment by rp-michaelpowers** [comment] 2019-04-16 14:37
@kinyat, thanks for the clarification. How are you generating your protobufs? When I take your examples and compile them I get a `my.another.srv.opps/opps.micro.go` that looks like this:

    import proto1 "my.srv.opps/proto"
    func RegisterOppsHandler(s server.Server, hdlr OppsHandler, opts ...server.HandlerOption) error {
	    type opps interface {
		    UseOpps(ctx context.Context, in *Request, out *proto1.MyMessage) error
	    }
    }

I created a gist of what I used to generate the above [here](https://gist.github.com/swedishborgie/31ec530a9ca9394466929251f1c68ce6). The output I got seems correct.

**Comment by swedishborgie** [comment] 2019-04-16 14:51
@kinyat, thanks for the clarification. How are you generating your protobufs? When I take your examples and compile them I get a `my.another.srv.opps/opps.micro.go` that looks like this:

    import proto1 "my.srv.opps/proto"
    func RegisterOppsHandler(s server.Server, hdlr OppsHandler, opts ...server.HandlerOption) error {
	    type opps interface {
		    UseOpps(ctx context.Context, in *Request, out *proto1.MyMessage) error
	    }
    }

I created a gist of what I used to generate the above [here](https://gist.github.com/swedishborgie/31ec530a9ca9394466929251f1c68ce6). The output I got seems correct.

**Comment by norganna** [comment] 2019-05-01 14:08
Hi, this is causing issues for us now.

We have existing code that imports protos that have the same go package name as the current service, and this breaks our current builds.

For a simple example of what I'm talking about, say we have two services `api.test` and `srv.test`. 
The apis proto imports the service's proto to use it's type.

We are now getting code generated like this:

```
func RegisterTestHandler(s server.Server, hdlr TestHandler, opts ...server.HandlerOption) error {
	type test interface {
		Test(ctx context.Context, in *test.TestRequest, out *test.TestResponse) error
	}
	type Test struct {
		test
	}
	h := &testHandler{hdlr}
	return s.Handle(s.NewHandler(&Test{h}, opts...))
}
```

This is causing issues because the `test` interface is conflicting with the `test` package name and  `test.TestRequest` / `test.TestResponse` in the interface won't resolve and causes a compilation error of:

```
proto/test/test.micro.go:80:37: test.TestRequest undefined (type test has no method TestRequest)
proto/test/test.micro.go:80:60: test.TestResponse undefined (type test has no method TestResponse)
```

May I humbly suggest that this may be readily resolved by changing the interface name to `testInterface` instead which avoids this conflict without having to mess with import names etc?

Something like this: https://github.com/micro/protoc-gen-micro/pull/43

**Comment by asim** [comment] 2019-05-01 14:31
I'm going to defer to @swedishborgie but can we not name an interface Interface, this is really redundant. 

Or better yet maybe we could just completely strip the need for this code? It was primarily there because people have a habit of badly naming their handlers or making them private and we needed a hacked workaround not only for this but also for some stream code generation.

**Comment by norganna** [comment] 2019-05-01 15:15
To be honest, I'm not even sure why this is here as in my generated code literally 5 lines up, I have a `type TestHandler interface {` which is exactly the same thing. I figured there must be a reason though.

**Comment by norganna** [comment] 2019-05-01 15:25
I've renamed it in my branch to use the `unexport(servName)+"Handler"` interface name just in case there is a good reason to not use the public Handler interface just above it.

**Comment by swedishborgie** [comment] 2019-05-01 17:40
I should have a change to look at this more closely tonight. If we can safely factor out the need to generate the internal service interface I'll look at throwing together a PR to do that.

I'll also look at the naming collision. @norganna can you share how you're generating the protobufs (e.g. an example of the `protoc` command you're using to generate the offending .micro.go files)? When I was testing this for the original issue my generator was namespacing imported packages with `protoN`, which would sidestep this problem.

**Comment by asim** [comment] 2019-05-01 21:26
We need to look at the multiple use cases here which include rpc streams and ensure the code generation continues to work for this. Otherwise realistically I have to backtrack any release pretty far to get back to functioning code.

**Comment by swedishborgie** [comment] 2019-05-01 21:59
Understood. I think the primary issue here is the package name collisions which both @norganna and @kinyat are both describing but that I'm having trouble replicating. I suspect it's tied to how protoc is being run. If I can replicate it then hopefully there's a straight forward way ahead from there.

If we're worried about the unintended consequences from trying to remove the internal service interface I think that's enough of a separate issue that we probably don't need to worry about it for the time being.

**Comment by norganna** [comment] 2019-05-01 22:21
Sure, here's a simple test case. Two proto files in the same folder `apitest.txt` and `srvtest.txt`. (n.b. I had to rename them to .txt to attach them, but it still works).

Compile with
```
protoc --proto_path=. --micro_out=. apitest.txt
```
[apitest.txt](https://github.com/micro/protoc-gen-micro/files/3136177/apitest.txt)
[srvtest.txt](https://github.com/micro/protoc-gen-micro/files/3136178/srvtest.txt)

**Comment by norganna** [comment] 2019-05-01 22:26
Just in case you need it, here is the generated code (with .txt appended):

[apitest.txt.micro.go.txt](https://github.com/micro/protoc-gen-micro/files/3136193/apitest.txt.micro.go.txt)

**Comment by swedishborgie** [comment] 2019-05-02 02:05
Ok, so after looking at this it looks like the primary source of both reported issues is the fact that since the upstream `generator.go` now always uses the `go_package` as the import package we'll have a name collision in any case there is an _imported package in a protobuf that has the same name as a service_'.

This coming up now is certainly a result of the change in behavior in `generator.go` but arguably the problem is really with how `plugin/micro/micro.go` generates names for internal types. This could have happened prior to the upstream re-base but it was less likely due to the fact people were likely to use protobuf package names that weren't likely to collide with types (e.g. `my.service.api`, now becomes `api`).

I think the generator's behavior of always using the `go_package` if set is probably the correct behavior. I think the easiest way to solve this without too much risk of breaking anything is to append an underscore to the generated inner interface name in Register*Handler() if we detect a name collision. This has the following advantages:
 * We're already doing this for reserved client names.
 * Things that aren't broken won't change.
 * [Package names should never contain _'s](https://golang.org/doc/effective_go.html#package-names).
 * Requires minimal changes to `generator.go`.

I generated PR #44 that takes the above approach. Let me know if you want me to take a different approach or if you want any changes.

**Comment by asim** [comment] 2019-05-02 02:38
No issues with that. Sounds like the best resolution. @norganna can you test the PR please

**Comment by norganna** [comment] 2019-05-02 05:08
This appears to be working properly for all the test cases I could come up with to try and trip it up.

I'm happy with this PR.

**Closed** 2019-05-02 13:55 UTC
