### ISSUE TITLE
Wrong generated file when timestamp included

### ISSUE THREAD

**Issue by coquebg** [micro/protoc-gen-micro#40] opened 2019-03-28 06:56 UTC
When trying to generate micro service with Protobuf well-known types, go micro generate files with nonexistent import paths:
``` proto
syntax = "proto3";

package test;

import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";

message TS {
  google.protobuf.Timestamp ts  = 1;
  string                    str = 2;
}

service SRV {
    rpc GetTS(google.protobuf.Any) returns (TS);
}
```

files are generated with

```bash
protoc \
	-I proto/ \
	-I ~/.local/include/\
	-I $GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
	--go_out=paths=source_relative:gen/go \
	--micro_out=paths=source_relative,plugins=grpc+micro:gen/go \
	--java_out=gen/java \
	--python_out=gen/python \
        proto/*.proto 
```

Micro-generated files contains following imports:
``` go
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google/protobuf" // !!! does not exists
import any "google/protobuf" // !!! does not exists
```
Note: GRPC/Java/Python files are generated w/o errors

**Comment by asim** [comment] 2019-03-28 07:06
@swedishborgie is this related to your change?

**Comment by swedishborgie** [comment] 2019-03-28 10:43
Based on the behavior described it's certainly possible this was my change. Let me debug this and see if I can figure out what's going on.

**Comment by swedishborgie** [comment] 2019-03-28 12:38
After playing around with this I can't seem to replicate the issue. I'm using the `timestamp.proto` and `any.proto` from the [official protobuf repo](https://github.com/protocolbuffers/protobuf):

        protoc \
            -I. \
            -I$GOPATH/src/github.com/protocolbuffers/protobuf/src \
            --micro_out=source_relative,plugins=grpc+micro:. \
            --go_out=source_relative:. \
            *.proto

With the [latest protoc-gen-micro](https://github.com/micro/protoc-gen-micro/tree/795aac5eb87c346b67b264ff7a514598d642c3b2) I'm getting the following generated source:

    package test

    import proto "github.com/golang/protobuf/proto"
    import fmt "fmt"
    import math "math"
    import _ "github.com/golang/protobuf/ptypes/timestamp"
    import any "github.com/golang/protobuf/ptypes/any"

    import (
        context "context"
        client "github.com/micro/go-micro/client"
        server "github.com/micro/go-micro/server"
    )


The generated source seems okay.

**Comment by vtolstov** [comment] 2019-03-28 13:02
i don't have such issue too (i'm use empty and any from wkt)

**Comment by asim** [comment] 2019-03-28 16:34
@coquebg are you using the latest code? go get -u?

**Comment by coquebg** [comment] 2019-03-30 04:56
Yes - I'm using the latest code

Here is a script I use to reproduce the issue (tested on 2 different linux machines)
```sh

DEST="gen"
GO_DEST=${DEST}/go
# GO_DEST=.

PROTOPATH=~/tools/protoc-3.7.1
# PROTOPATH=~/tools/protoc-3.6.1

### Cleanup
rm -rf ${DEST}/go
rm -f go.mod go.sum
find ${DEST} -type f -name '*.pg.go' -o -name '*.micro.go' -exec rm -f {} \;

### Get latest tools
go get -u github.com/golang/protobuf/protoc-gen-go
go get -u github.com/micro/protoc-gen-micro

# go mod init test
mkdir -p ${GO_DEST} proto
cat <<_EOF_ > proto/test.proto
syntax = "proto3";

package test;

import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";

message TS {
  google.protobuf.Timestamp ts  = 1;
  string                    str = 2;
}

service SRV {
    rpc GetTS(google.protobuf.Any) returns (TS);
}
_EOF_

${PROTOPATH}/bin/protoc \
    -I proto/ \
	-I ${PROTOPATH}/include \
    -I ~/.local/include \
	--go_out=paths=source_relative:${GO_DEST} \
	--micro_out=paths=source_relative:${GO_DEST} \
	proto/*.proto

echo
grep 'google/protobuf' ${GO_DEST}/*.go &&
echo -e "\n:( ......\n"
```

**Comment by swedishborgie** [comment] 2019-03-30 13:32
Ok! That helps, thanks @coquebg. I've been able to reproduce your issue after running through your script.

It looks like the `paths=source_relative` piece that is triggering the issue. I tested and this issue was present before #37 got merged, so I don't think it's related to that change. I should have time in the next couple days to see if I can figure out what's going on.

**Comment by swedishborgie** [comment] 2019-03-31 03:16
I think I've got the issued narrowed down to [one line](https://github.com/micro/protoc-gen-micro/blob/master/generator/generator.go#L1369):

    filename := fd.goFileName(g.pathType)

It looks like upstream purposely doesn't take the path type into account [when determining the import path](https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L533). It looks like this issue was present upstream and was fixed with golang/protobuf@9d4962b4dc40a899c435fe1aaec48e683b4300ef. The simplest and most expedient fix is to change that line to:

    filename := fd.goFileName(pathTypeImport)

But it looks like there's a lot of upstream changes that fix numerous issues related to code generation especially around imports. So it may make sense to try to pull in the upstream changes. @asim do you have a preference?

**Comment by asim** [comment] 2019-03-31 03:17
I do not have a preference, let's go with whatever is the easiest to maintain in the long term.

**Comment by swedishborgie** [comment] 2019-03-31 03:26
Sounds good. If you don't mind I'll take a swing at pulling in the upstream generator.go and re-applying the micro specific pieces. It looks like those guys have smoothed out a lot of the rough edges in the last year.

**Comment by asim** [comment] 2019-03-31 03:28
Yes please, really appreciate!

**Comment by swedishborgie** [comment] 2019-04-01 15:32
I just submitted a PR that I believe fixes the issue and merges in the upstream changes.

@coquebg can you please try my fork and see if it resolves your issue?

    go get -u github.com/swedishborgie/protoc-gen-micro

**Comment by coquebg** [comment] 2019-04-02 17:37
It works - all produced files are OK

BTW: It seems there is a problem with modules in your repo
```bash
go get -u github.com/swedishborgie/protoc-gen-micro
go: github.com/swedishborgie/protoc-gen-micro@v0.6.0: parsing go.mod: unexpected module path "github.com/micro/protoc-gen-micro"
go get: error loading module requirements
```
git clone + build + install works however ....

**Comment by swedishborgie** [comment] 2019-04-02 18:08
Thanks for testing! I'd expect the go.mod to be broken since I forked the micro repo and didn't change the module path. It's pointing to the wrong repository. It shouldn't be a problem after the pull request is merged.

**Comment by asim** [comment] 2019-04-02 18:19
So from what I can tell we're saying this is good and we can merge the PR?

**Comment by swedishborgie** [comment] 2019-04-02 18:25
Yep, I think so. The PR fixes this issue for myself and for @coquebg and didn't create any regressions in the scenarios I tested.

**Comment by asim** [comment] 2019-04-02 18:27
Thanks to the both of you for this! Good to have others who can handle this stuff too.

**Closed** 2019-04-02 18:27 UTC
